### PR TITLE
Drop support for Python 3.8

### PR DESCRIPTION
**Pull request by Luc1412**
## Summary

This PR drops support for Python 3.8 since it has been deprecated since 2024-10-07. It removes the classifier, updates the workflow python version to 3.9 and bumps the minimum Python version to 3.9 within `pyproject.toml`.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by trevorflahardy** [comment]
Dropping Python 3.8 has one large implication not addressed, typing-wise: Python 3.9 brought on type hinting generics in standard collections (with PEP 585).

The library should ideally be updated to account for this as well to ensure strict typing compliances. It may be worth looking into [`pyupgrade`](https://github.com/asottile/pyupgrade) to help with this, but I don't feel this PR should be merged until this is addressed.

**Comment by Luc1412** [comment]
@trevorflahardy I updated the code accordingly with `pyupgrade`. Should we ignore this in git blame?

**Comment by trevorflahardy** [comment]
> @trevorflahardy I updated the code accordingly with `pyupgrade`. Should we ignore this in git blame?

Could be useful, yes, but not needed imo. Up to you either work fine 👍

**Review by trevorflahardy — COMMENTED** [review]
Looks good :)

**Review by trevorflahardy — APPROVED** [review]

**Pull request merged**
