### PR TITLE
Added Examples For Beginners To Learn From

### PR DESCRIPTION
**Pull request by NeilShah2026**

### CODE REVIEW

**Comment by NeilShah2026** [comment]
@Luc1412

**Comment by Luc1412** [comment]
It's not intended to use raw_data. The main reason for this would be saving the data in json format.

**Comment by Luc1412** [comment]
Also these 2 examples are the same. You could just get the battle pass level when fetching stats.

**Comment by NeilShah2026** [comment]
@Luc1412 
Ok, so should I change it, or just close the pull?

**Comment by Luc1412** [comment]
If you like you could provide an example in the examples directory. It should be an Python file eg. stats.py where you show the intended usage.

**Comment by NeilShah2026** [comment]
ok

**Pull request closed without merging**
